name: Linux Desktop

on:
  workflow_dispatch:

jobs:
  desktop:
    runs-on: ubuntu-24.04

    steps:

      - name: Install desktop
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tigervnc-standalone-server

      - name: Setup VNC
        run: |
          mkdir -p ~/.vnc

          echo "12345678" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

          echo '#!/bin/bash
          startxfce4 &' > ~/.vnc/xstartup

          chmod +x ~/.vnc/xstartup

      - name: Start desktop
        run: |
          vncserver :1 -geometry 1280x720

      - name: Show info
        run: |
          echo "DESKTOP STARTED"
          echo "DISPLAY :1"
          echo "PORT 5901"

      - name: Keep alive
        run: |
          sleep 21600
