name: Desktop Server

on:
  workflow_dispatch:

jobs:
  desktop:
    runs-on: ubuntu-latest

    steps:
      - name: Install desktop
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies tigervnc-standalone-server

      - name: Start desktop
        run: |
          mkdir -p ~/.vnc
          echo "password" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

          vncserver :1 -geometry 1280x720

      - name: Keep alive
        run: |
          sleep 21600
