name: Free Server

on:
  workflow_dispatch:

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - name: Check server
        run: |
          echo "Сервер запущен"
          uname -a
          lscpu
          free -h

      - name: Keep alive
        run: |
          sleep 21600
